parameters:
    millwright_semaphore.manager.class: Millwright\Semaphore\Model\SemaphoreManager
    millwright_semaphore.try_count: 5
    millwright_semaphore.sleep_time: 1
    millwright_semaphore.expire_interval: 15

services:
    millwright_semaphore.manager:
        class: %millwright_semaphore.manager.class%
        arguments:
            - @millwright_semaphore.adapter
            - %millwright_semaphore.try_count%
            - %millwright_semaphore.sleep_time%
            - %millwright_semaphore.expire_interval%
